== Containerization basics

[.notes]
--
* Guide the class to thinking about the need for process isolation (via kernel namespaces etc), filesystem provisioning (via Docker images), and resource consumption limitations (via cgroups)
* Hint questions if the class is stuck:
* Do you trust the other processes running on this host? Should they trust you? (leads to need for process isolation)
* Will your process' dependencies be available on this host? Are you sure? (leads to need for docker images)
* How much resources can you reasonably consume on this host? (leads to need for cgroup limitations)         
--

=== Learning objectives

By the end of this module, trainees will be able to

* Describe what a container is in terms of processes and isolation tools
* Use the key commands for interacting with Docker containers

=== Containers are processes

[.keyword]#Containers# are processes sandboxed by

* Kernel namespaces
* Control Groups
* Root priviledge management & syscall restrictions (Linux)
* VM isolation (Windows)

[.notes]
--
* Fundamentally, containers are just processes living on the host, isolated primarily by kernel namespaces, and control groups for resource isolation.
* Linux containers can also be subject to restrictions on what root privileges and system calls they are allowed to make, by application of a linux security module.
* On the Windows side, containers enhance their isolation by running in ultra-light-weight VMs.
--

=== Linux kernel namespaces

* DEFAULT
** Process IDs
** Network stacks
** Inter-process communications
** Mount points
** Hostnames

* OPTIONAL
** User IDs

[.notes]
--
* The baseline tool for creating containers is the kernel namespace. Kernel namespaces create distinct representations of things like PID trees, user spectra, network stacks and mount points; processes live in exactly one namespace, and are only able to interact with the broader system via the representation encapsulated therein.
* By analogy: an un-namespaced system is like when airplanes used to have just one TV in the cabin everyone would look up at to watch the in-flight movie. Everyone shared the device, and everyone saw the same thing.
* Introducing namespaces is like putting seatback TVs in front of every passenger. Now everyone has their own private devices and sees their own thing, which is hidden from their neighbors.
* In the same way, a namespaced process has all their own resources - their own iptables rules and eth0 device, their own mount points, their own PID tree - and processes in other namespaces aren't allowed to touch or even see these resources.       
--

=== Linux PID kernel namespace

image::03_containerization_basics/pid-tree.svg[width=50%]

[.notes]
--
* For example, PID namespaces make the first process in the namespace appear as the root of a process tree to all other processes in that namespace, which will be its children.
* Meanwhile, processes in the parent namespace see these processes with PID numbers like any other process in the parent PID namespace.
* In this way, processes in the child namespace aren't able to find information about processes in the parent namespace, but the child namespace remains transparent from the perspective of the parent namespace.
* Stopping the PID 1 of a child namespace and stopping the container are the exact same thing.
* Isolating host system resources, rather than creating a whole new virtual machine, is where the high performace of containers comes from. Think of it like building a little wall around a patch of sand in a sandbox; the area marked off can itself be thought of as a new sandbox, but no new sand has been acquired.
            
--

=== Optional Linux isolation features

* Control groups: limit memory & CPU
* Root priviledge management: acceptlist root powers
* System call management: acceptlist available system calls
* Linux Security Modules: mandatory filesystem access control

[.notes]
--
* In addition to the default kernel namespaces, a number of other linux technologies can be imposed on your containers to restrict their privileges.
* All production deployments should take advantage of control groups, to limit how much memory and CPU a container can consume.
* Root privileges and system calls are governed by whitelist, which can be configured per-container
* Linux security modules allow the creation of access control rules for filesystem paths and objects within the container.
--

[.dark_background.demo.background]
=== icon:task[role=moby_icon] Instructor demo: Process isolation

See the demo

* Process isolation

in the exercise book

[.dark_background.exercise.background]
=== icon:task[role=moby_icon] Exercise: Container Basics

Work through

* Running and inspecting a container
* Interactive containers
* Detached containers and Logging
* Starting, stopping, inspecting and deleting cotnainers

In the exercise book.

++++
<h2 id="exercise_container_basics" class="timer"></h2>
++++

=== Container lifecycle

image::03_containerization_basics/container-lifecycle.svg[]

[.notes]
--
* The rectangles display the state of the container and the arrow labels show the Docker command used to change the container state.
* The container lifecycle always begins in the CREATED state. A container in this state has a private filesystem set up on disk (more on this in the next chapter) and metadata defined regarding what process it is to encapsulate and how, but it not yet running. When the process in question begins running, the container transitions to the UP state.
* If a containerized process exits, the container transitions to the EXITED state. It can normally be restarted with a start command.
* Finally, Docker containers can enter a PAUSED state of suspension imposed by control group freezing. This suspension technique (unlike using SIGSTOP and SIGCONT) can't be caught by the process, ensuring that pausing a container doesn't disrupt the process it containerizes.        
--

=== Container logs

* STOUD and STERR for a container process
* `docker container logs <container_name>`

[.notes]
--
* STDOUT and STDERR of whatever process is PID 1 in a container are logged by Docker, and available via `docker container logs`
--

=== Container basics takeaways

* Single process constrained by kernel namespaces, control groups and other Linux technologies
* Private & ephemeral filesystem and data

[.notes]
--
* The key conceptual take-aways for container basics are the first two points; the container's main process, which it labels PID 1, will stop the container when it itself stops; and writing to the container's file system writes only to that container, not the underlying image; soon we'll learn more about these underlying images, and how to manipulate them.
* Everything else we learned in this unit is basic creation, deletion and investigation syntax.
--

=== Further reading

* List of container commands: link:http://dockr.ly/2iLBV2I[http://dockr.ly/2iLBV2I]
* Getting started with containers: link:http://dockr.ly/2gmxKWB[http://dockr.ly/2gmxKWB]
* Start containers automatically: link:http://dockr.ly/2xB8sMl[http://dockr.ly/2xB8sMl]
* Limit a container's resources: link:http://dockr.ly/2wqN5Nn[http://dockr.ly/2wqN5Nn]
* Isolate containers with a user namespace: link:http://dockr.ly/2gmyKdf[http://dockr.ly/2gmyKdf]
* Keep containers alive during daemon downtime: link:http://dockr.ly/2emLwb5[http://dockr.ly/2emLwb5]
* Intro to Windows Containers: link:https://dockr.ly/2CTYhYb[https://dockr.ly/2CTYhYb]

[.notes]
--
additional resources about containers
--