== Container Volumes

=== Discussion: Managing data

If a container generates at lot of data, where should it be stored? +
What if you need to provision data to a container?

[.notes]
--
* Guide the class to thinking about the fact that so far, containers and images don't provide a practical way to manage data that lives longer than the lifetime of a container.
* Hint questions if the class is stuck:
* Should you write a lot of data to the container layer? That's currently the only place we've learned about in this workshop where you can write data to at container run time. Why wouldn't you want to do this?
* Should you provision data to a container by including that data in the underlying image? Again, this is the only option we've seen so far. Why wouldn't you want to do this? 
--

=== Learning objectives

By the end of this module, trainees will be able to

* Define a volume and identify its primary use cases
* Describe advantages and potential secuity risks of mounting volumes and host directories

=== Volume usecases

Volumes provide a R/W path [.keyword]#separate from the layered filesystem#.

* [.keyword]#Mount# data at container startup
* [.keyword]#Persist# data when a container is deleted
* [.keyword]#Share# data between containers
* [.keyword]#Speed up# I/O by circumventing the union filesystem

[.notes]
--
* Volumes primarily provide a way to handle data that has a longer lifecycle than an individual container, by providing a writable location separate from the container's union filesystem.
* For example, if a container needs access to a large body of files, those files can be mounted into a running container as a volume, avoiding the need to create a (potentially huge) image with that data baked in.
* If a container is creating or collecting data as it runs, it should be stored in a volume, since that volume will survive the deletion of the container.
* Furthermore, volumes can be a more performant choice for write heavy workloads for the same reason. Rather than searching the layers of the union filesystem and performing a copy on write operation when writing a file, I/O in a volume simply reads and writes the relevant file, without the added overhead.
--

=== Basic volumes

* [.keyword]#Named#: managed by Docker; filesystem independent; user-specified identifier
* [.keyword]#Anonymous#: managed by Docker; filesystem independent; randomly-generated identifier
* [.keyword]#Host mounted#: mount a specific path on the host; DIY management

[.notes]
--
* There are two high-level methods for mounting volumes into containers: named volumes, and host mounts.
* In the named volume case, Docker will create and manage a directory on your host for your volume, using the 'docker volume' CLI commands.
* Host mounts specify a particular path on the host to mount into a container. This is useful if there's something host specific you want to provide to the container, but requires you to manage the host's filesystem directly and depends on the path in question actually being meaningful on that host, potentially affecting portability.
--

[.dark_background.demo.background]
=== icon:task[role=moby_icon] Instructor demo: Volumes

See the demo

* Basic Volume Usage

in the exercise book.

=== Volumes in Containerfile

* [.keyword]#VOLUME# instructions creates a mount point
* Can specify arguments in a JSON array or string
* Cannot map volumes to host directories
* Volumes are initialized when the container is executed

[.notes]
--
* VOLUME is another Dockerfile instruction available to designate a directory inside a container as a volume to be persisted on the host.
* Note that this syntax does not allow for the specification of a host path, since that would break our all-important portability; there's no guarantee that path will exist on any arbitrary machine in a meaningful way.
* Docker automatically creates a volume (directory) on the host for each volume that is declared in the Dockerfile. The name of such a host volume is a sha256. The data that is then stored inside those volumes inside the container is mapped/persisted to the host FS.
--

[source,dockerfile]
----
FROM nginx:latest
...
# string example
VOLUME /myvolume

# string example with multiple volumes
VOLUME /www/website1 /www/website2

# JSON example
VOLUME ["myvol1", "myvol2"]
...
----

=== Volumes and security

* Point of ingress to the host and other containers
* Don't mount things unnecessarily
* Use the [.keyword]#:ro# flag whenever possible
* Linu: in-memory [.keyword]#tmpfs# mounts available

[.notes]
--
* Volumes are the first thing we've seen so far that pierce the isolation we carefully crafted between containers, the host, and other containers. A malicious actor can inject files from one container to another, and to the host, if care is not taken.
* Mount volumes and directories only as needed, and use the :ro flag when a container is only a passive consumer of data. Better yet, ask if there's a way to separate out reader and writer containers, to keep write access to volumes as tightly restricted as possible.
* Also for those running linux hosts, it's also possible to mount purely in-memory volumes to a container; anything written here will never be written to disk, and will be released when the container is deleted. This is a good option for persisting sensitive data while a container is running.
--

[.dark_background.exercise.background]
=== icon:task[role=moby_icon] Exercise: Volumes usecases

Work through

* Database Volumes

in the exercise book.


++++
<h2 id="exercise_container_volumes_database" class="timer"></h2>
++++

=== Container volumes takeaways

* Volumes persist data beyond the container lifecycle
* Volumes bypass the copy-ob-write system (better for write-heavy containers)

[.notes]
--
* The most important take home message for volumes, is that this is where persistent data should go - not in containers, which come and go rapidly.
* Also, volumes are separate from the union file system; changes to volumes do not precipitate changes to images, and vice versa.
--

=== Further reading

* How to use volumes: link:http://dockr.ly/2vRZBDG[http://dockr.ly/2vRZBDG]
* Troubleshoot volume errors: link:http://dockr.ly/2vyjvbP[http://dockr.ly/2vyjvbP]
* Docker volume reference: link:http://dockr.ly/2ewrlew[http://dockr.ly/2ewrlew]

[.notes]
--
additional resources about volumes
--
