== Docker system commands

[.notes]
--
* So far, we've encountered commands to interact with individual images and containers; in practice however, a Docker workflow will generate a lot of containers and images. 
* In this module, we'll introduce some tools for managing your entire collection of images and containers on a node.
--

=== Learning objectives

By the end of this module, trainees will be able to

* Execut cleanup commands
* Locate Docker system information

=== Cleanup commands

[source,bash]
----
$ docker system df
TYPE           TOTAL    ACTIVE   SIZE        RECLAIMABLE
Images         39       2        9.01 GB     7.269 GB (80%)
Containers     2        2        69.36 MB    0 B
----

* `docker system prune`

more limited...

* `docker image prune [--filter "foo=bar"]`
* `docker container prune [--filter "foo=bar"]`
* `docker volume prune [--filter "foo=bar"]`
* `docker network prune [--filter "foo=bar"]`

[.notes]
--
* under heavy use the docker host might consume a load of resources or disk space. To find out with type of elements occupy how much space we can use the `docker system df` command. It tells us exactly how much space images, container and volumes currently occupy and how much of it is claimable.
* to claim back unused space from the Docker host we can use the command `docker system prune`. It will try to remove dangling images, stopped containers and unused volumes and networks in one go.
* we also have the more specialized `prune`` commands that only remove unused items of the given type
* Prune commands can also be filtered by label in all cases, before a timestamp via 'until' for everything but volumes, and also by 'dangling' for images, for even more restricted pruning.
--

=== Inspect the system

[source,bash]
----
$ docker system info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 105
Server Version: 17.03.0-ee
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: ybmqksh6fm627armruq0e8id1
 Is Manager: true
 ClusterID: 2rbf1dv6t5ntro2fxbry6ikr3
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
----

[.notes]
--
* We can use the `docker system info` command to get very detailed information about the current Docker host. This information includes but is not limited to images, containers, swarm mode, networks and volumes.
* When looking at the output, can you identify:
** how many images are on your machine?
** What version of containerd are you running?
** Whether Docker is running in swarm mode?
--

=== System events

[source,bash]
----
$ docker system events
2017-01-25T16:57:48.553596179-06:00 container create 30eb630790d44052f26c1081...
2017-01-25T16:57:48.556718161-06:00 container attach 30eb630790d44052f26c1081...
2017-01-25T16:57:48.698190608-06:00 network connect de1b2b40f522e69318847ada3...
2017-01-25T16:57:49.062631155-06:00 container start 30eb630790d44052f26c1081d...
2017-01-25T16:57:49.164526268-06:00 container die 30eb630790d44052f26c1081dbf...
2017-01-25T16:57:49.613422740-06:00 network disconnect de1b2b40f522e69318847a...
2017-01-25T16:57:49.815845051-06:00 container destroy 30eb630790d44052f26c108...
----

Generates events with `docker container run --rm apline echo 'Hello world'`

[.notes]
--
* `docker system info` gave us some mostly-static metadata about our docker platform; if we want to watch things live, we can take advantage of Docker's event reporting via `docker system events`.
* please note that the output generated by the `docker system events` command can also be filtered and custom formatted by using according command arguments `--filter` and `format`
* Image from image:http://www.bing.com/src/modules/06-system-commands/images/search?view=detailV2&ccid=xHDtNSak&id=F6B851CB5DF9FCB90FD4C4FBF86073617E979328&q=monitoring&simid=608004200364248188&selectedIndex=0&qft=+filterui%3alicense-L1+filterui%3aimagesize-medium&ajaxhist=0[]
--

[.dark_background.exercise.background]
=== icon:task[role=moby_icon] Exercise: System commands

Work through

* Cleaning up Docker resources
* Inspecting Commands

in the exercise book.


++++
<h2 id="exercise_docker_system_commands" class="timer"></h2>
++++

=== Discussion

* What is the origin of dangling container image layers?
* What are potential pitfalls automating system cleanup, and how can we avoid them?
* Questions?

[.notes]
--
* When a layer is no longer part of any tagged image, typically happens when a name and tag is reused after changing a Dockerfile.
* Deleting containers without grabbing their logs first, deleting volumes that have valuable info just because they weren't currently attached to anything. Avoid by using label-based filters when pruning.
--

=== Further reading

* System commands reference: link:http://dockr.ly/2eMR53i[http://dockr.ly/2eMR53i]

