== Running & Inspecting Containers

By the end of this exercise, you should be able to:

* Start a container
* List containers in multiple ways
* Query the docker command line help
* Remove containers

=== Interactive Containers

Create and start a new CentOS 7 container running ping to 8.8.8.8. Docker will downlaod the CentOS 7 image since you do not have it available locally.

[source,shell]
----
[centos@node-0 ~]$ docker container run centos:7 ping 8.8.8.8

Unable to find image 'centos:7' locally
7: Pulling from library/centos
a02a4930cb5d: Pull complete 
Digest: sha256:184e5f35598e333bfa7de10d8fb1cebb5ee4df5bc0f970bf2b1e7c7345136426
Status: Downloaded newer image for centos:7
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=108 time=7.07 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=108 time=7.11 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=108 time=7.03 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=108 time=7.09 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=108 time=7.01 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=108 time=7.00 ms
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5006ms
rtt min/avg/max/mdev = 7.008/7.056/7.110/0.039 ms
----

Press `CTRL+C` after a few pings. This stops and exits the container.

=== Detached Containers

This first container sent its STDOUT to your terminal. Create a second container, this time in detached mode:

[source,shell]
----
[centos@node-0 ~]$ docker container run --detach centos:7 ping 8.8.4.4

8aef3d0d411c7b02532292ec3267a54f9258eaafb71d3d73a8ad41e702bd35a2
----

Instead of seeing the executed command (`ping 8.8.4.4`), Docker engine displays a long hexidecimal number, which is the full container ID of your new container. The container is running detached, which means the container is running as a background process, rather than printing its STDOUT to your terminal.

=== Listing running Containers

List the running Docker containers using the `docker container ls` container command. You will see only one container running.

[source,shell]
----
[centos@node-0 ~]$ docker container ls

CONTAINER ID IMAGE    COMMAND        CREATED       STATUS        PORTS  NAMES
8aef3d0d411c centos:7 "ping 8.8.4.4" 3 minutes ago Up 3 minutes         zen_jang
----

=== Listing all Containers

Now you know that the docker container ls command only shows running containers. You can show all containers that exist (running or stopped) by using `docker container ls --all`. Your container ID and name will vary. Note that you will see two containers: a stopped container and a running container.

[source,shell]
----
[centos@node-0 ~]$ docker container ls --all 

CONTAINER ID  IMAGE     COMMAND         CREATED        STATUS         NAMES
8aef3d0d411c  centos:7  "ping 8.8.4.4"  2 minutes ago  Up 2 minutes   zen_jang
00f763b9308d  centos:7  "ping 8.8.8.8"  4 minutes ago  Exited (0)...  inspiring_cheb
----

Where did those names come from? All containers have names, which in most Docker CLI commands can be substituted for the container ID as we'll see in later exercises. By default, containers get a randomly generated name of the form `<adjective>_<scientist / technologist>`, but you can choose a name explicitly with the `--name` flag in `docker container run`.

=== Naming Containers

Start up another detached container, this time giving it a name "opendnsping".

[source,shell]
----
[centos@node-0 ~]$ docker container run --detach --name opendnsping \
                   centos:7 ping 208.67.222.222

3bdc61a95e76fdfe2597ef18aa00321a53dcdc9c36b2db97fbe738f8a623ecad
----

List all your containers again. You can see all of the containers, including your new one with your customized name.

[source,shell]
----
[centos@node-0 ~]$ docker container ls --all

CONTAINER ID IMAGE    COMMAND               CREATED        STATUS         NAMES
3bdc61a95e76 centos:7 "ping 208.67.222.222" 23 seconds ago Up 22 seconds  opendnsping
8aef3d0d411c centos:7 "ping 8.8.4.4"        4 minutes ago  Up 14 minutes  zen_jang
00f763b9308d centos:7 "ping 8.8.8.8"        9 minutes ago  Exited (0)...  inspirin...
----

=== Remove exited Containers

Next, remove the exited container. To do this, use `docker container rm <container ID>`. In the example above, the Docker container ID is `00f763b9308d`. You only need as many characters as to uniquely identify this container from all the others.

[source,shell]
----
[centos@node-0 ~]$ docker container rm <container ID>

00f763b9308d
----

=== Remove running Containers

Now try to remove one of the other Docker containers using the same command. It does not work. Why?

[source,shell]
----
[centos@node-0 ~]$ docker container rm <container ID>

Error response from daemon: You cannot remove a running container 
3bdc61a95e76fdfe2597ef18aa00321a53dcdc9c36b2db97fbe738f8a623ecad. 
Stop the container before attempting removal or force remove
----

You can see that running containers are not removed. You'll have to look for an option to remove a running container. In order to find out the option you need to do a force remove, check the command line help. To do this with the `docker container rm` command, use the `--help` option:

[source,shell]
----
[centos@node-0 ~]$ docker container rm --help

Usage: docker container rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers

Options:
 -f, --force     Force the removal of a running container (uses SIGKILL)
 -l, --link      Remove the specified link
 -v, --volumes   Remove the volumes associated with the container
----

*Help works with all Docker commands* Not only can you use `--help` with `docker container rm`, but it works on all levels of docker commands. For example, `docker --help` provides you will all available docker commands, and `docker container --help` provides you with all available container commands.

Now, run a force remove on the running container you tried to remove in the two previous steps. This time it works.

[source,shell]
----
[centos@node-0 ~]$ docker container rm --force <container ID> 

8aef3d0d411c
----

Start another detached container pinging 8.8.8.8, with the name `pinggoogledns`.

[source,shell]
----
[centos@node-0 ~]$ docker container run --detach --name pinggoogledns \
                   centos:7 ping 8.8.8.8

38e121e629611daa0726a21d634bc5189400377d82882cc6fd8a3870dc9943a0
----

Now that you've finished your testing, you need to remove your containers. In order to remove all of them at once, you want to get only the container IDs. Look at docker container ls --help to get the information you need:

[source,shell]
----
[centos@node-0 ~]$ docker container ls --help

Usage:    docker container ls [OPTIONS]

List containers

Aliases:
  ls, ps, list

Options:
  -a, --all           Show all containers (default shows just running)
  -f, --filter filter Filter output based on conditions provided
  --format string     Pretty-print containers using a Go template
  -n, --last int      Show n last created containers (includes all states)
  -l, --latest        Show the latest created container (includes all states)
      --no-trunc      Don't truncate output
  -q, --quiet         Only display numeric IDs
  -s, --size          Display total file sizes
----

To get only the container IDs, use the `--quiet` option. If you want to use only the container IDs of all existing containers to perform an action on, you can use `--quiet` with the `--all` option.

[source,shell]
----
[centos@node-0 ~]$ docker container ls --all --quiet

3bdc61a95e76     
38e121e62961
----

Since we are done running pings on the public DNS servers, kill the containers. To do this, use the syntax `docker container rm --force <containerID>`. However, this only kills one container at a time. We want to kill all the containers, no matter what state the containers are in. To get this information, you will need to use the output from docker container ls `--quiet` `--all`. To capture this output within the command, use `$(...)` to nest the listing command inside the docker container rm command.

[source,shell]
----
[centos@node-0 ~]$ docker container rm --force \
    $(docker container ls --quiet --all)

3bdc61a95e76     
38e121e62961
----

=== Conclusion

This exercise taught you how to start, list, and kill containers. In this exercise you ran your first containers using `docker container run`, and how they are running commands inside the containers. You also learned to how to list your containers, and how to kill the containers using the command `docker container rm`. If you run into trouble, you've learned that the `--help` option can provide you with information that could help get you answers.