== Creating Images with Dockerfiles (2/2)
By the end of this exercise, you should be able to:

* Define a default process for an image to containerize by using the `ENTRYPOINT` or `CMD` `Dockerfile` commands
* Understand the differences and interactions between `ENTRYPOINT` and `CMD`

=== Setting Default Commands
Add the following line to the bottom of your `Dockerfile` from the last exercise:

[source,Dockerfile]
----
CMD ["ping", "127.0.0.1", "-c", "5"]
----
This sets ping as the default command to run in a container created from this image, and also sets some parameters for that command.

Rebuild your image:

[source,shell]
----
[user@node myimage]$ docker image build -t myimage .
----
Run a container from your new image with no command provided:

[source,shell]
----
[user@node myimage]$ docker container run myimage
----
You should see the command provided by the `CMD` parameter in the Dockerfile running.

Try explicitly providing a command when running a container:

[source,shell]
----
[user@node myimage]$ docker container run myimage echo "hello world"
----
Providing a command in `docker container run` overrides the command defined by `CMD`.

Replace the `CMD` instruction in your `Dockerfile` with an `ENTRYPOINT`:

[source,Dockerfile]
----
ENTRYPOINT ["ping"]
----
Build the image and use it to run a container with no process arguments:

[source,shell]
----
[user@node myimage]$ docker image build -t myimage .
[user@node myimage]$ docker container run myimage
----
You'll get an error. What went wrong?

Try running with an argument after the image name:

[source,shell]
----
[user@node myimage]$ docker container run myimage 127.0.0.1
----
You should see a successful ping output. Tokens provided after an image name are sent as arguments to the command specified by `ENTRYPOINT`.

=== Combining Default Commands and Options
Open your `Dockerfile` and modify the `ENTRYPOINT` instruction to include 2 arguments for the ping command:

[source,Dockerfile]
----
ENTRYPOINT ["ping", "-c", "3"]
----
If `CMD` and `ENTRYPOINT` are both specified in a `Dockerfile`, tokens listed in `CMD` are used as default parameters for the `ENTRYPOINT` command. Add a `CMD` with a default IP to ping:

[source,Dockerfile]
----
CMD ["127.0.0.1"]
----
Build the image and run a container with the defaults:

[source,shell]
----
[user@node myimage]$ docker image build -t myimage .
[user@node myimage]$ docker container run myimage
----
You should see it pinging the default IP, 127.0.0.1.

Run another container with a custom IP argument:

[source,shell]
----
[user@node myimage]$ docker container run myimage 8.8.8.8
----
This time, you should see a ping to 8.8.8.8. Explain the difference in behavior between these two last containers.

=== Conclusion
In this exercise, we encountered the `Dockerfile` commands `CMD` and `ENTRYPOINT`. 
These are useful for defining the default process to run as `PID 1` inside the container right in the `Dockerfile`, making our containers more like executables and adding clarity to exactly what process was meant to run in a given image's containers.