---
- name: "Prepare Docker Training environment"
  hosts: localhost
  gather_facts: no
  vars:
      linux_user: ubuntu
  tasks:
    - name: "Install Packages"
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ item }}"
        cache_valid_time: 86400 #One day
      with_items:
        - pip
        - docker.io
        - docker-compose
        - nano
        - zip
        - unzip
        - tar

    - name: "Ensure group 'docker' exists"
      become: yes
      ansible.builtin.group:
        name: docker
        state: present

    - name: "Add the user to docker group"
      become: yes
      ansible.builtin.user:
        name: "{{ linux_user }}"
        groups: "docker,sudo"
        append: yes

    - name: "Ensure Docker Service is started"
      ansible.builtin.systemd:
        state: started
        name: docker